### Method 1 : Using `pipeline`

In [30]:
from transformers import pipeline

ppl = pipeline("question-answering")

question = "What is Nupedia?"
context = """
Nupedia was a free, web-based encyclopedia project.
It was founded by Jimmy Wales and Larry Sanger.
Nupedia is considered the predecessor of Wikipedia.
"""

result = ppl(
    question=question,
    context=context
)

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 564e9b5 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.
Device set to use cpu


In [31]:
print(result)

{'score': 0.5423746705055237, 'start': 13, 'end': 51, 'answer': 'a free, web-based encyclopedia project'}


### Method 2 : Using `AutoModelForQuestionAnswering` and `AutoTokenizer` 

In [43]:
from transformers import AutoModelForQuestionAnswering,AutoTokenizer
import torch

In [ ]:
ckpt = "bert-large-uncased-whole-word-masking-finetuned-squad"

model = AutoModelForQuestionAnswering.from_pretrained(ckpt)

tokenizer = AutoTokenizer.from_pretrained(ckpt)

question = "What is Nupedia?"
context = """
Nupedia was a free, web-based encyclopedia project.
It was founded by Jimmy Wales and Larry Sanger.
Nupedia is considered the predecessor of Wikipedia.
"""

inputs = tokenizer(question,context,return_tensors='pt')

Some weights of the model checkpoint at bert-large-uncased-whole-word-masking-finetuned-squad were not used when initializing BertForQuestionAnswering: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForQuestionAnswering from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForQuestionAnswering from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [48]:
with torch.no_grad():
    outputs = model(**inputss)



In [49]:
outputs

QuestionAnsweringModelOutput(loss=None, start_logits=tensor([[-5.8855, -5.0089, -6.8464, -6.8071, -8.5481, -9.1613, -9.1909, -5.8854,
         -0.3178, -5.6781, -5.6334,  0.2020,  4.8596,  3.1841, -2.2530,  3.2283,
         -5.1140, -2.1944,  1.7781, -2.0029, -6.3476, -1.3307, -6.9688, -4.8262,
         -7.3600, -5.1684, -6.9545, -7.7956, -6.0297, -7.1784, -7.5832, -5.8853,
          0.9096, -5.4603, -5.1671, -3.1388,  0.1729,  1.7554,  1.3154, -5.2914,
          1.3439, -6.2040, -5.8853]]), end_logits=tensor([[-0.7006, -4.3879, -5.6606, -7.0502, -6.7526, -6.1493, -6.8758, -0.7005,
         -4.6255, -5.1035, -2.4324, -4.6937, -3.7785, -1.3826, -3.0311, -2.4826,
         -6.1172, -1.9739,  2.9043,  5.3902,  2.9015, -4.2074, -5.1119, -4.4165,
         -5.6767, -5.8032, -4.4501, -6.0663, -6.0149, -6.3597, -3.6914, -0.7004,
         -4.8279, -5.4813, -2.1522, -5.8197, -5.6985, -5.2033, -1.2048, -2.9249,
          3.5750,  2.4387, -0.7009]]), hidden_states=None, attentions=None)

In [50]:
outputs['start_logits'].numpy()

array([[-5.8854704 , -5.008898  , -6.846439  , -6.807089  , -8.548111  ,
        -9.161278  , -9.190941  , -5.8854113 , -0.31775376, -5.6780667 ,
        -5.633442  ,  0.20202821,  4.8596296 ,  3.1841424 , -2.253005  ,
         3.2282877 , -5.113993  , -2.194407  ,  1.7780578 , -2.0028737 ,
        -6.3476295 , -1.3306957 , -6.9687567 , -4.82621   , -7.360012  ,
        -5.1683683 , -6.9545403 , -7.795623  , -6.0296755 , -7.178401  ,
        -7.5831513 , -5.8853445 ,  0.90960836, -5.460279  , -5.16712   ,
        -3.138823  ,  0.1729353 ,  1.7554102 ,  1.3153528 , -5.291364  ,
         1.3438816 , -6.2039766 , -5.885345  ]], dtype=float32)

In [58]:
start_index = outputs['start_logits'].argmax()


In [59]:
start_index

tensor(12)

In [61]:
end_index = outputs['end_logits'].argmax()

In [62]:
end_index

tensor(19)

In [63]:
inputss['input_ids']

tensor([[  101,  2054,  2003, 16371,  5669,  2401,  1029,   102, 16371,  5669,
          2401,  2001,  1037,  2489,  1010,  4773,  1011,  2241, 12204,  2622,
          1012,  2009,  2001,  2631,  2011,  5261,  3575,  1998,  6554,  6369,
          2121,  1012, 16371,  5669,  2401,  2003,  2641,  1996,  8646,  1997,
         16948,  1012,   102]])

In [65]:
output_ids = inputss['input_ids'][0][start_index:end_index+1]

In [66]:
output_ids

tensor([ 1037,  2489,  1010,  4773,  1011,  2241, 12204,  2622])

In [69]:
" ".join(tokenizer.convert_ids_to_tokens(output_ids))

'a free , web - based encyclopedia project'

In [33]:
inputs

{'input_ids': array([[  101,  2054,  2003, 16371,  5669,  2401,  1029,   102, 16371,
         5669,  2401,  2001,  1037,  2489,  1010,  4773,  1011,  2241,
        12204,  2622,  1012,  2009,  2001,  2631,  2011,  5261,  3575,
         1998,  6554,  6369,  2121,  1012, 16371,  5669,  2401,  2003,
         2641,  1996,  8646,  1997, 16948,  1012,   102]]), 'token_type_ids': array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]), 'attention_mask': array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [34]:
inputss = tokenizer(question,context,return_tensors='pt')

In [25]:
inputss

{'input_ids': tensor([[  101,  2054,  2003, 16371,  5669,  2401,  1029,   102, 16371,  5669,
          2401,  2001,  1037,  2489,  1010,  4773,  1011,  2241, 12204,  2622,
          1012,  2009,  2001,  2631,  2011,  5261,  3575,  1998,  6554,  6369,
          2121,  1012, 16371,  5669,  2401,  2003,  2641,  1996,  8646,  1997,
         16948,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [35]:
inputss['input_ids'][0]

tensor([  101,  2054,  2003, 16371,  5669,  2401,  1029,   102, 16371,  5669,
         2401,  2001,  1037,  2489,  1010,  4773,  1011,  2241, 12204,  2622,
         1012,  2009,  2001,  2631,  2011,  5261,  3575,  1998,  6554,  6369,
         2121,  1012, 16371,  5669,  2401,  2003,  2641,  1996,  8646,  1997,
        16948,  1012,   102])

In [36]:
tokenizer.convert_ids_to_tokens(inputss['input_ids'][0])

['[CLS]',
 'what',
 'is',
 'nu',
 '##ped',
 '##ia',
 '?',
 '[SEP]',
 'nu',
 '##ped',
 '##ia',
 'was',
 'a',
 'free',
 ',',
 'web',
 '-',
 'based',
 'encyclopedia',
 'project',
 '.',
 'it',
 'was',
 'founded',
 'by',
 'jimmy',
 'wales',
 'and',
 'larry',
 'sang',
 '##er',
 '.',
 'nu',
 '##ped',
 '##ia',
 'is',
 'considered',
 'the',
 'predecessor',
 'of',
 'wikipedia',
 '.',
 '[SEP]']